### ISSUE TITLE
IJCK R2C12

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/pyked-ncm-2017#29]
> Is it possible to create for example two common-properties composition blocks A and B and
refer to them in the DataPoint keys?

**Comment by bryanwweber** [comment]
Ref: 

From Kyle:
> Regarding two composition blocks inside common-properties, I think this would be possible, as long as field are given different YAML tags. Perhaps we should add a test for this.

**Comment by bryanwweber** [comment]
I actually don't think this is possible, unless the blocks were named differently. That is,

```
common-properties:
  compositon: &compA
    - ...
  composition: &compB
    - ...
```
is prohibited AFAIK (or perhaps the keys would be merged, it might depend on the YAML library implementation). However, if we allow any property in the `common-properties`, then the two composition blocks don't have to be named `composition` and this would work fine.

**Comment by bryanwweber** [comment]
See also https://github.com/pr-omethe-us/PyKED/issues/67

**Comment by kyleniemeyer** [comment]
I *think* this would work:
```yaml
common-properties:
  compositionA: &compA
    - ...
  compositionB: &compB
    - ...
```
since the data points would have
```yaml
  composition: *compA
```

... right?
